# baseline_AdaIN MODULE & Not detach
add_seg : 1
seg_detach: 0
add_edge : 0
edge_thres : 1
add_selayer : 0
generate_eyeball : 0
feature_channels : 153
style_dim : 8 # AdaIN Output dimension
input_concat : 0
only_edge : 0