[package]
name = "evaluation"
version = "0.1.0"
edition = "2021"

[dependencies]
ommatidia = { path = "ommatidia" }
serde = "1.0"
toml = "0.5"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"

[workspace]
members = ["ommatidia"]
