[ommatidia]
threads = 4
buffer_size = 128

# All the available hosts. If skipped, ommatidita will try to stick to a local host.
[[host]]
name = "default"
host = "127.0.0.1"
port = 1234

[[detector]]
name = "PuRe - Default"
image = "pure:1.0"
host = "default"
config = { width = 120, height = 120 }

# The following elements are the datasets
[[data]]
name = "Example dataset"
type = "filesystem"
pattern = ["test/test12.png", "test/*/*.jpg"]
