[ommatidia]
threads = 4
buffer_size = 128

# All the available hosts. If skipped, ommatidita will try to stick to a local host.
[[engines]]
name = "default"
host = "host.docker.internal"
port = 2375

[[detectors]]
name = "pure"
image = "pure:0.1"
#host = "default"
config = { width = 120, height = 120 }

# The following elements are the datasets
[[datasets]]
name = "Example dataset"
type = "filesystem"
patterns = [
    "local_data/Pictures/anleitung_1.png",
    "local_data/Pictures/Bild1.png",
]
